initializeAutocomplete = (id) ->
  element = document.getElementById(id)
  if element
    autocomplete = new (google.maps.places.Autocomplete)(element, types: [ 'geocode' ])
    google.maps.event.addListener autocomplete, 'place_changed', onPlaceChanged
  return

onPlaceChanged = ->
  place = @getPlace()
  # console.log(place);  // Uncomment this line to view the full object returned by Google API.
  for i of place.address_components
    component = place.address_components[i]
    for j of component.types
      # Some types are ["country", "political"]
      type_element = document.getElementById(component.types[j])
      if type_element
        type_element.value = component.long_name
  return

google.maps.event.addDomListener window, 'page:update', ->
  initializeAutocomplete 'user_input_autocomplete_address'
  return

# ---
# generated by js2coffee 2.1.0